### ISSUE TITLE
Broken links in `formatted_data_links/README.md`

### ISSUE THREAD

**Issue by My-laniaKeA** [Hughes-Genome-Group/deepC#4]
Thanks for sharing the code of your work! 
I found broken data links in `formatted_data_links/README.md`. These links lead to a 404 error page. I think the links need to be updated.

**Comment by rschwess** [comment]
Hi Sorry for the WAY late reply. The public data access area is currently not available. I am chasing down where to access the data now. In the mean time you can use the data in the [Zenodo archive](https://zenodo.org/records/5785805), almost all files listed in the `formatted_data_links/README.md` are also saved there. I updated the README to reflect the current state.

**Comment by rschwess** [comment]
Data links updated and working.
