### ISSUE TITLE
Could you update the dala link please?

### ISSUE THREAD

**Issue by seraphimangel77** [Hughes-Genome-Group/deepC#5]
Thanks for sharing the code of your work!
I found broken data links in formatted_data_links/README.md. These links lead to a 404 error page. 
 I would like to cite your paper and data in my article. Could you please update the data link?

**Comment by rschwess** [comment]
Hi Sorry for the late reply. The public data access area is currently not available. I am chasing down where to access the data now. In the meantime, you can use the data in the [Zenodo archive](https://zenodo.org/records/5785805), almost all files listed in the `formatted_data_links/README.md` are also saved there. I updated the README to reflect the current state.

**Comment by rschwess** [comment]
Data links updated and working.
